services:
  app:
    container_name: skedoodle-app
    image: ghcr.io/eugenioenko/skedoodle:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=file:/app/data/skedoodle.db
      - HTTP_PORT=3013
      - WS_PORT=3014
      - CORS_ORIGIN=https://${SKEDOODLE_DOMAIN}
      - OIDC_ISSUER_URL=${OIDC_ISSUER_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}

networks:
  web:
    external: true
